### ISSUE TITLE
При переходе на API v3 перестали приниматься вложения от мобильного

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_forest_violations#23]
```
Exception when serving /api/component/file_upload/upload
Traceback (most recent call last):
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/ngw_admin/ngw/nextgisweb/nextgisweb/resource/api.py", line 204, in resource_exception_tween
    response = handler(request)
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 82, in tm_tween
    reraise(*exc_info)
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 63, in tm_tween
    response = handler(request)
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/home/ngw_admin/ngw/nextgisweb/nextgisweb/file_upload/view.py", line 41, in upload_post
    if 'files[]' in request.POST \
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/webob/request.py", line 807, in POST
    vars = MultiDict.from_fieldstorage(fs)
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/webob/multidict.py", line 92, in from_fieldstorage
    obj.add(field.name, decode(value))
  File "/home/ngw_admin/ngw/env/lib/python2.7/site-packages/webob/multidict.py", line 78, in <lambda>
    decode = lambda b: b.decode(charset)
  File "/home/ngw_admin/ngw/env/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte

```

В мобильном код отправки оттачей не менялся. С v2 работатет.

**Comment by BishopGIS** [comment]
Ошибка была на стороне мобильного приложения.
